### ISSUE TITLE
Remove Software Foundations solutions, etc.

### ISSUE THREAD

**Issue by langston-barrett** [uhub/awesome-coq#3]
This list might be useful if it were significantly more selective. It doesn't help Coq users to point them to 100+ repos of solutions to exercises in SF. Similarly, any sort of "experimental", "personal", or "just for fun" repos could be removed.

**Comment by ccding** [comment]
Thank you so much for pointing this out. I have deleted many of them. Let me know if there is any left.

**Comment by langston-barrett** [comment]
Thanks!
