### ISSUE TITLE
Add Mathematical Components

### ISSUE THREAD

**Issue by XVilka** [uhub/awesome-coq#8]
The book https://github.com/math-comp/mcb

**Comment by anton-trunov** [comment]
I guess you meant https://github.com/math-comp/mcb as your second link

**Comment by sanxiyn** [comment]
It has been added now.

**Comment by ccding** [comment]
could you please submit a pull request?

**Comment by sanxiyn** [comment]
What? It's already there. Search for "Mathematical Components" in README.md. The only thing remaining is to close this issue, which I can't do.
